Repository skodaconnect/myskoda, pull requests merged in 2024-12, with the labels that each got.

#260 Fix Auxiliary Heater for ICE, add outside_temperature
  fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml
  myskoda/models/auxiliary_heating.py
  myskoda/models/info.py
  myskoda/myskoda.py
  myskoda/vehicle.py
Labels: bug, enhancement

#262 Add capability FLEET_SUPPORTED
  fixtures/octavia_iv_2021_nx56xc_combi_rs.yaml
  fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml
  myskoda/models/info.py
Labels: bug

#268 added outsideTemperature into AirConditioning class
  fixtures/Octavia2023_w_aux_heating.yaml
  fixtures/citigoe_iv_2021_ne142e2_best_of.yaml
  fixtures/djapollo_enyaq_85_2025.yaml
  fixtures/kamiq.yaml
  fixtures/karoq-se-l_2023.yaml
  fixtures/kodiaq_2024_ps7d6z_exclusive.yaml
  fixtures/nu74nv_karoq_expired_subscription.yaml
  fixtures/nx53l5_octavia_2024_combi_deepsleep_0.8.3.yaml
  fixtures/octavia_2022.yaml
  fixtures/octavia_iv_2021_nx56xc_combi_rs.yaml
  fixtures/prior99_enyaq_iv60_idle_full_battery.yaml
  fixtures/prior99_octavia_2018.yaml
  fixtures/skoda_octavia_combi_2023.yaml
  fixtures/sonar98_Enyaq_iV80_2022_software_3.0.yaml
  fixtures/superb_2024_3v35wz_liftback_l_and_k.yaml
  fixtures/superb_iv_2020_3v35xc_liftback_l_and_k.yaml
  fixtures/superb_iv_2021_3v54xc.yaml
  fixtures/superb_iv_combi_2022_3V53XC_standing_still.yaml
  fixtures/webspider_enyaq_iv80_parked_deep_sleep_positioning_off.yaml
  myskoda/models/air_conditioning.py
  myskoda/models/auxiliary_heating.py
Labels: bug

#263 Introduce exponential backoff for MQTT reconnect
  myskoda/mqtt.py
  myskoda/myskoda.py
Labels: bug

#276 Update used API endpoints with 0.14.4
  docs/api_endpoints.md
Labels: documentation

#281 Fix MQTT
  myskoda/mqtt.py
  tests/fixtures/mqtt/mqtt_auth.passwd
Labels: bug

#282 Add new capability UNAVAILABILITY_STATUSES
  myskoda/models/info.py
Labels: bug

#285 add RESET_SPIN into VehicleState
  myskoda/models/info.py
Labels: bug

#284 Add exception for redirect to marketing consent
  myskoda/auth/authorization.py
Labels: bug

#290 add CableLock feature (set_auto_unlock_plug)
  myskoda/auth/authorization.py
  myskoda/cli/__init__.py
  myskoda/cli/operations.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  tests/test_operations.py
Labels: enhancement

#293 Add set-minimum-charge-limit feature
  docs/api_endpoints.md
  myskoda/cli/__init__.py
  myskoda/cli/operations.py
  myskoda/const.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  tests/test_operations.py
Labels: enhancement

#294 update currently implemented api_endpoints
  docs/api_endpoints.md
Labels: documentation

#303 Change MQTT connection to behave more like MySkoda app
  myskoda/const.py
  myskoda/mqtt.py
Labels: bug

#302 send current timestamp inside departure info request
  myskoda/rest_api.py
  tests/test_rest_api.py
Labels: bug
