Repository skodaconnect/myskoda, pull requests merged in 2025-04, with the labels that each got.

#407 Update vehicle cache with MQTT event data
  myskoda/auth/authorization.py
  myskoda/mqtt.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  myskoda/vehicle.py
  pyproject.toml
Labels: enhancement, maintenance

#412 Add new API endpoints from MySkoda v8.2.0 app
  docs/api_endpoints.md
Labels: documentation

#411 Debouncer + Refresh API data automatically on MQTT events
  README.md
  docs/events.md
  docs/refreshing_data.md
  mkdocs.yaml
  myskoda/cli/mqtt.py
  myskoda/const.py
  myskoda/models/common.py
  myskoda/mqtt.py
  myskoda/myskoda.py
  myskoda/utils.py
  tests/test_mqtt.py
  tests/test_utils.py
Labels: enhancement, breaking

#413 Fix: user.nickname is optional
  myskoda/models/user.py
Labels: bug
