Repository skodaconnect/myskoda, pull requests merged in 2025-09, with the labels that each got.

#471 Ignore code that doesnt need testing
  myskoda/mqtt.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  myskoda/vehicle.py
Labels: maintenance

#472 Add ignition_on field to vehicle_connection_status
  fixtures/webspider_enyaq_2021_5AZJJ2_80.yaml
  myskoda/models/vehicle_connection_status.py
Labels: bug

#467 Implement charging history
  docs/api_endpoints.md
  myskoda/cli/__init__.py
  myskoda/cli/requests.py
  myskoda/cli/utils.py
  myskoda/models/charging_history.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  myskoda/utils.py
  pyproject.toml
  tests/fixtures/other/charging-history.json
  tests/test_rest_api.py
  tests/test_utils.py
  uv.lock
Labels: enhancement

#476 Add fixture for Elroq Sportline
  fixtures/elroq_2025_PYLQK2_Sportline.yaml
Labels: fixtures

#479 Add 2 new capabilities
  fixtures/elroq_2025_PYLQK2_Sportline.yaml
  myskoda/models/info.py
Labels: maintenance

#481 fix: add dataclass for vehicle-connection-offline message
  myskoda/models/event/vehicle.py
Labels: bug
