Repository skodaconnect/myskoda, pull requests merged in 2025-03, with the labels that each got.

#368 Bump MQTT libraries for compatibility with HA2025.3
  poetry.lock
  pyproject.toml
Labels: dependencies

#376 Add ONLINE_REMOTE_UPDATE capability
  myskoda/models/info.py
Labels: bug

#379 Force new Vehicle to be returned
  myskoda/myskoda.py
Labels: bug

#378 Add example info about "Get ordered vehicle details" endpoint
  docs/rest.md
Labels: documentation

#366 Add brand configuration for future support of multiple brands
  myskoda/auth/authorization.py
  myskoda/const.py
  myskoda/myskoda.py
  tests/conftest.py
  tests/test_auth.py
Labels: enhancement

#384 Add capability ACCIDENT_DAMAGE_MANAGEMENT
  myskoda/models/info.py
Labels: bug

#389 Update API documentation with responses of various GET requests
  docs/api_endpoints.md
Labels: documentation

#388 Initial implementation of charging profiles
  myskoda/anonymize.py
  myskoda/auth/authorization.py
  myskoda/cli/__init__.py
  myskoda/cli/gen_fixtures.py
  myskoda/cli/requests.py
  myskoda/models/chargingprofiles.py
  myskoda/models/fixtures.py
  myskoda/mqtt.py
  myskoda/myskoda.py
  myskoda/rest_api.py
  tests/fixtures/enyaq/charging-profiles.json
  tests/test_rest_api.py
Labels: enhancement

#402 Add replies from new URLs
  docs/api_endpoints.md
Labels: documentation
