Repository skodaconnect/myskoda, pull requests merged in 2025-05, with the labels that each got.

#423 Add start/stop ventilation (air-conditioning)
  docs/api_endpoints.md
  myskoda/cli/__init__.py
  myskoda/cli/operations.py
  myskoda/myskoda.py
  myskoda/rest_api.py
Labels: enhancement

#419 Add new fixture for Enyaq 85, 2025 facelift
  fixtures/enyaq_2025_5azjk2_85.yaml
Labels: fixtures

#426 feat: implement vehicle connection state endpoint
  docs/api_endpoints.md
  myskoda/anonymize.py
  myskoda/cli/__init__.py
  myskoda/cli/requests.py
  myskoda/models/vehicle_connection_status.py
  myskoda/myskoda.py
  myskoda/rest_api.py
Labels: enhancement

#428 docs: add contribution styleguide
  CONTRIBUTING.md
Labels: documentation

#427 fix: Add tests for VehicleConnectionStatus and store in Vehicle object
  myskoda/myskoda.py
  myskoda/vehicle.py
  tests/fixtures/other/vehicle-connection-status.json
  tests/test_rest_api.py
Labels: bug

#431 Add fixture for Elroq 85
  fixtures/elroq_85_2025.yaml
Labels: fixtures

#433 fix: add vehicle_connection_status to fixture generator
  myskoda/models/fixtures.py
  myskoda/myskoda.py
Labels: bug

#434 chore: add readiness as a seperate API call
  myskoda/myskoda.py
Labels: maintenance

#439 fix: add missing LOYALTY_PROGRAM user capability
  myskoda/models/user.py
Labels: bug

#438 BREAKING CHANGE: MQTT Event model overhaul
  myskoda/__init__.py
  myskoda/cli/mqtt.py
  myskoda/event.py
  myskoda/models/__init__.py
  myskoda/models/event/__init__.py
  myskoda/models/event/account.py
  myskoda/models/event/base.py
  myskoda/models/event/operation.py
  myskoda/models/event/service.py
  myskoda/models/event/vehicle.py
  myskoda/models/service_event.py
  myskoda/models/vehicle_event.py
  myskoda/mqtt.py
  myskoda/myskoda.py
  pyproject.toml
  tests/conftest.py
  tests/test_mqtt.py
  tests/test_service_event.py
  uv.lock
Labels: breaking
